### ISSUE TITLE
Address discovery using SRV DNS Records

### ISSUE THREAD

**Issue by ndelta0** [ttalk-chat/TTalk#16]
Using a DNS record would allow for an easier connection, i.e. the server owner could set up the `_ttalk._tcp.example.org` SRV record, which would allow the client to connect (if it were to support DNS record discovery) just by providing the `example.org` address and no port (since the port is contained within the DNS record).

**Comment by roxxel** [comment]
Hi! Your proposal looks like good idea. I'll look into ways to implement this
